spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/school_lms_db
spring.datasource.username=root
spring.datasource.password=SANKALPAsmt@285
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081